#pragma once

#include "EDMProcessMotionIntent.h"
#include <type_traits>

// EDM47 is a same-owner, bounded SHADOW command handoff. Applied means only
// that the local shadow consumer copied a velocity. Completed is reserved for
// a Drain, after a later owner clock observation. Neither is Motion, PDO, NIC,
// drive, position, return or physical standstill evidence. EDM27 retains its
// synthetic admission fixture; EDM28 owns the separate real RT request and
// feedback contract for the finite, unloaded single-Z diagnostic.
namespace EDM47
{
    enum class Domain : std::uint8_t { Shadow = 1U };
    enum class CommandKind : std::uint8_t { Velocity, Drain };
    enum class ReceiptStage : std::uint8_t { None, Accepted, Applied, Completed };
    enum class ExecutionState : std::uint8_t { Idle, Running, Blocked, Draining, Completed, Cancelled, Fault };
    enum class DrainStatus : std::uint8_t { Wait, Ready, Invalid };
    enum class Reason : std::uint8_t
    {
        None, InvalidLifecycle, InvalidConfig, ScopeMismatch, SourceMismatch,
        InvalidIntent, InvalidPacket, Clock, Stale, Sequence, Busy,
        ReceiptMismatch, AuthorityLost, CounterOverflow, AwaitLaterClock,
        NonFresh, Cancelled, RetiredSession
    };
    using ExecutionReason = Reason;
    struct Packet
    {
        Domain domain = Domain::Shadow;
        CommandKind kind = CommandKind::Velocity;
        EDM46::Scope scope{};
        EDM26::LiveSourceIdentity sourceIdentity{};
        std::uint64_t commandSequence = 0U, intentSequence = 0U;
        std::uint64_t sourceSequence = 0U, sourceTimeMs = 0U, observedAtMs = 0U, issuedAtMs = 0U;
        EDM46::IntentFrame frame = EDM46::IntentFrame::None;
        EDM25::ProcessAction action = EDM25::ProcessAction::Wait;
        double signedSpeedMmMin = 0.0;
        std::array<double, EDM46::AxisSlots> axisSpeedMmMin{};
    };
    struct Receipt
    {
        Packet packet{};
        ReceiptStage stage = ReceiptStage::None;
        // Accepted has no consumer publication (zero). Applied/Completed
        // publications are generated by the separate shadow consumer.
        std::uint64_t publication = 0U, atMs = 0U;
    };
    template<class T> inline bool AllSpeedsZero(const T& value) noexcept
    {
        for (double speed : value.axisSpeedMmMin) if (speed != 0.0) return false;
        return true;
    }
    inline bool SamePacket(const Packet& a, const Packet& b) noexcept
    {
        return a.domain == b.domain && a.kind == b.kind && EDM46::SameScope(a.scope, b.scope) &&
            EDM46::SameSource(a.sourceIdentity, b.sourceIdentity) &&
            a.commandSequence == b.commandSequence && a.intentSequence == b.intentSequence &&
            a.sourceSequence == b.sourceSequence && a.sourceTimeMs == b.sourceTimeMs &&
            a.observedAtMs == b.observedAtMs && a.issuedAtMs == b.issuedAtMs &&
            a.frame == b.frame && a.action == b.action && a.signedSpeedMmMin == b.signedSpeedMmMin &&
            a.axisSpeedMmMin == b.axisSpeedMmMin;
    }
    inline bool ValidSource(const EDM26::LiveSourceIdentity& source) noexcept
    {
        const bool physical = source.source == EDMGap::Source::PHYSICAL;
        return (physical || source.source == EDMGap::Source::SIMULATED) &&
            source.profileRevision && source.maxAgeMs && (!physical ||
                (source.calibrationConfirmed && source.calibrationRevision && source.adIndex));
    }
    inline bool ValidInitial(const EDM46::Config& config, const EDM46::Scope& scope,
        const EDM46::IntentSnapshot& initial, std::uint64_t nowMs) noexcept
    {
        return EDM46::ValidateConfig(config) && EDM46::ValidScope(scope) &&
            config.frame.frameGeneration == scope.frameGeneration && EDM46::SameScope(scope, initial.scope) &&
            ValidSource(initial.sourceIdentity) && initial.state == EDM46::IntentState::AwaitingFresh &&
            !initial.ready && !initial.acceptedFreshSample && initial.sequence == 0U &&
            initial.observedAtMs == nowMs && initial.sourceTimeMs <= nowMs &&
            (initial.sourceSequence || initial.sourceTimeMs == 0U) && EDM46::AllSpeedsZero(initial) &&
            initial.frame == EDM46::IntentFrame::None && initial.action == EDM25::ProcessAction::Wait;
    }
    // Both ledger and consumer validate the frozen payload. This does not
    // replace EDM46's process-state checks, nor add a machine envelope.
    inline bool ValidPacket(const Packet& p, const EDM46::Config& config,
        const EDM46::Scope& scope, const EDM26::LiveSourceIdentity& source, std::uint64_t nowMs) noexcept
    {
        if (p.domain != Domain::Shadow || !EDM46::SameScope(p.scope, scope) ||
            !EDM46::SameSource(p.sourceIdentity, source) || p.commandSequence == 0U ||
            p.issuedAtMs > nowMs || p.observedAtMs > p.issuedAtMs || p.sourceTimeMs > p.observedAtMs ||
            !std::isfinite(p.signedSpeedMmMin) ||
            std::fabs(p.signedSpeedMmMin) > config.maximumScalarMmMin) return false;
        for (std::size_t axis = 0U; axis < EDM46::AxisSlots; ++axis)
            if (!std::isfinite(p.axisSpeedMmMin[axis]) ||
                std::fabs(p.axisSpeedMmMin[axis]) > config.maximumAxisMmMin[axis] ||
                ((config.frame.selectedAxisMask & (1U << axis)) == 0U && p.axisSpeedMmMin[axis] != 0.0)) return false;
        if (p.kind == CommandKind::Drain)
            return p.frame == EDM46::IntentFrame::None && p.action == EDM25::ProcessAction::Wait &&
                p.signedSpeedMmMin == 0.0 && AllSpeedsZero(p);
        if (p.kind != CommandKind::Velocity || p.intentSequence == 0U || p.sourceSequence == 0U ||
            nowMs - p.issuedAtMs > source.maxAgeMs || nowMs - p.observedAtMs > source.maxAgeMs ||
            nowMs - p.sourceTimeMs > source.maxAgeMs) return false;
        using A = EDM25::ProcessAction;
        using F = EDM46::IntentFrame;
        const double speed = p.signedSpeedMmMin;
        bool path = false, z = false;
        switch (p.action)
        {
        case A::Wait: case A::ReturnBlocked:
            return p.frame == F::None && speed == 0.0 && AllSpeedsZero(p);
        case A::ServoAdvance: if (speed <= 0.0) return false; path = true; break;
        case A::ServoRetreat: if (speed >= 0.0) return false; path = true; break;
        case A::ShortRetreat: if (speed > 0.0) return false; path = true; break;
        case A::FlushRetreat:
            path = p.frame == F::MachiningPath && speed <= 0.0;
            z = p.frame == F::MachineZ && speed >= 0.0; break;
        case A::FlushReturn:
            path = p.frame == F::MachiningPath && speed >= 0.0;
            z = p.frame == F::MachineZ && speed <= 0.0; break;
        default: return false;
        }
        if ((!path && !z) || (path && p.frame != F::MachiningPath) ||
            (z && !config.frame.machineZConfirmed)) return false;
        for (std::size_t axis = 0U; axis < EDM46::AxisSlots; ++axis)
        {
            const double expected = path ? speed * config.frame.machiningUnit[axis] :
                (axis == config.frame.machineZAxis ? speed : 0.0);
            if (p.axisSpeedMmMin[axis] != expected) return false;
            if (path && speed != 0.0 && config.frame.machiningUnit[axis] != 0.0 && expected == 0.0) return false;
        }
        return true;
    }
    struct ExecutionSnapshot
    {
        ExecutionState state = ExecutionState::Idle;
        Reason reason = Reason::None;
        EDM46::Scope scope{};
        EDM26::LiveSourceIdentity sourceIdentity{};
        Receipt lastAccepted{}, lastApplied{}, lastCompleted{};
        std::uint64_t acceptedCount = 0U, appliedCount = 0U, completedCount = 0U;
        std::uint64_t neutralizedCount = 0U, cancelledBeforeApply = 0U, cancelledAfterApply = 0U;
        std::array<double, EDM46::AxisSlots> axisSpeedMmMin{};
        bool pending = false;
        constexpr bool PhysicalMotionEnabled() const noexcept { return false; }
        constexpr bool PhysicalDischargeEnabled() const noexcept { return false; }
        constexpr bool PhysicalStopProven() const noexcept { return false; }
        constexpr bool DriveAcknowledged() const noexcept { return false; }
    };
    class ExecutionLedger
    {
    public:
        const ExecutionSnapshot& Snapshot() const noexcept { return s_; }
        bool Reset() noexcept
        {
            if (s_.state == ExecutionState::Running || s_.state == ExecutionState::Blocked ||
                s_.state == ExecutionState::Draining || s_.pending) return false;
            const auto retired = retiredSession_, command = commandFloor_, publication = publicationFloor_;
            *this = ExecutionLedger{};
            retiredSession_ = retired; commandFloor_ = command; publicationFloor_ = publication; return true;
        }
        bool Start(const EDM46::Config& config, const EDM46::Scope& scope,
            const EDM46::IntentSnapshot& initial, std::uint64_t nowMs) noexcept
        {
            if (s_.state != ExecutionState::Idle) return Fail(Reason::InvalidLifecycle);
            if (scope.session <= retiredSession_) return Fail(Reason::RetiredSession);
            if (!ValidInitial(config, scope, initial, nowMs)) return Fail(Reason::InvalidConfig);
            config_ = config; s_.scope = scope; s_.sourceIdentity = initial.sourceIdentity;
            retiredSession_ = scope.session; lastNowMs_ = nowMs;
            intentFloor_ = initial.sequence; sampleFloor_ = initial.sourceSequence;
            sampleTimeFloor_ = initial.sourceTimeMs; observedFloor_ = initial.observedAtMs;
            s_.state = ExecutionState::Running; return true;
        }
        bool Accept(const Packet& packet, std::uint64_t nowMs) noexcept
        {
            if (s_.state != ExecutionState::Running && s_.state != ExecutionState::Blocked) return Fail(Reason::InvalidLifecycle);
            if (s_.pending) return Fail(Reason::Busy);
            if (nowMs < lastNowMs_) return Fail(Reason::Clock);
            if (!ValidPacket(packet, config_, s_.scope, s_.sourceIdentity, nowMs)) return Fail(Reason::InvalidPacket);
            if (packet.commandSequence <= commandFloor_ || packet.issuedAtMs < lastNowMs_ ||
                (packet.kind == CommandKind::Velocity && (packet.intentSequence <= intentFloor_ ||
                 packet.sourceSequence <= sampleFloor_ || packet.sourceTimeMs <= sampleTimeFloor_ ||
                 packet.observedAtMs < observedFloor_))) return Fail(Reason::Sequence);
            if (packet.kind == CommandKind::Drain && (packet.intentSequence != intentFloor_ ||
                packet.sourceSequence != sampleFloor_ || packet.sourceTimeMs != sampleTimeFloor_ ||
                packet.observedAtMs != observedFloor_)) return Fail(Reason::Sequence);
            if (s_.acceptedCount == Maximum()) return Fail(Reason::CounterOverflow);
            commandFloor_ = packet.commandSequence; lastNowMs_ = nowMs;
            intentFloor_ = packet.intentSequence; sampleFloor_ = packet.sourceSequence;
            sampleTimeFloor_ = packet.sourceTimeMs; observedFloor_ = packet.observedAtMs;
            s_.lastAccepted = Receipt{packet, ReceiptStage::Accepted, 0U, nowMs};
            ++s_.acceptedCount; s_.pending = true; s_.reason = Reason::None;
            s_.state = packet.kind == CommandKind::Drain ? ExecutionState::Draining : ExecutionState::Running;
            return true;
        }
        bool Apply(const Receipt& receipt, std::uint64_t nowMs) noexcept
        {
            if (!s_.pending || (s_.state != ExecutionState::Running && s_.state != ExecutionState::Draining))
                return Fail(Reason::InvalidLifecycle);
            if (nowMs < lastNowMs_ || receipt.atMs < s_.lastAccepted.atMs || receipt.atMs > nowMs)
                return Fail(Reason::Clock);
            if (receipt.stage != ReceiptStage::Applied || !SamePacket(receipt.packet, s_.lastAccepted.packet) ||
                receipt.publication == 0U || receipt.publication <= publicationFloor_)
                return Fail(Reason::ReceiptMismatch);
            if (!ValidPacket(receipt.packet, config_, s_.scope, s_.sourceIdentity, nowMs)) return Fail(Reason::InvalidPacket);
            if (s_.appliedCount == Maximum()) return Fail(Reason::CounterOverflow);
            s_.lastApplied = receipt; publicationFloor_ = receipt.publication;
            ++s_.appliedCount; s_.pending = false; lastNowMs_ = nowMs;
            s_.axisSpeedMmMin = receipt.packet.axisSpeedMmMin; s_.reason = Reason::None; return true;
        }
        bool Complete(const Receipt& receipt, std::uint64_t nowMs) noexcept
        {
            if (s_.state != ExecutionState::Draining || s_.pending || s_.lastApplied.stage != ReceiptStage::Applied ||
                s_.lastApplied.packet.kind != CommandKind::Drain) return Fail(Reason::InvalidLifecycle);
            if (nowMs < lastNowMs_ || receipt.atMs <= s_.lastApplied.atMs || receipt.atMs > nowMs)
                return Fail(Reason::Clock);
            if (receipt.stage != ReceiptStage::Completed || !SamePacket(receipt.packet, s_.lastApplied.packet) ||
                receipt.publication <= publicationFloor_) return Fail(Reason::ReceiptMismatch);
            if (s_.completedCount == Maximum()) return Fail(Reason::CounterOverflow);
            s_.lastCompleted = receipt; publicationFloor_ = receipt.publication; ++s_.completedCount;
            s_.state = ExecutionState::Completed; s_.reason = Reason::None; lastNowMs_ = nowMs; return true;
        }
        // Recoverable nonfresh observation. The wrapper zeros the consumer
        // first; no command/receipt or completion is fabricated here.
        bool Neutralize() noexcept
        {
            if (s_.state != ExecutionState::Running && s_.state != ExecutionState::Blocked) return Fail(Reason::InvalidLifecycle);
            if (s_.neutralizedCount == Maximum()) return Fail(Reason::CounterOverflow);
            if (s_.pending)
            {
                if (s_.cancelledBeforeApply == Maximum()) return Fail(Reason::CounterOverflow);
                ++s_.cancelledBeforeApply;
            }
            s_.pending = false; s_.axisSpeedMmMin.fill(0.0); ++s_.neutralizedCount;
            s_.state = ExecutionState::Blocked; s_.reason = Reason::NonFresh; return true;
        }
        void Cancel() noexcept
        {
            s_.axisSpeedMmMin.fill(0.0);
            if (s_.state == ExecutionState::Idle || s_.state == ExecutionState::Cancelled) return;
            if (s_.pending && s_.cancelledBeforeApply != Maximum()) ++s_.cancelledBeforeApply;
            else if ((s_.state == ExecutionState::Running || s_.state == ExecutionState::Blocked ||
                s_.state == ExecutionState::Draining) && s_.lastApplied.stage == ReceiptStage::Applied &&
                s_.cancelledAfterApply != Maximum()) ++s_.cancelledAfterApply;
            s_.pending = false; s_.state = ExecutionState::Cancelled; s_.reason = Reason::Cancelled;
        }
        void Abort(Reason reason) noexcept { Cancel(); s_.state = ExecutionState::Fault; s_.reason = reason; }
        std::uint64_t CommandFloor() const noexcept { return commandFloor_; }
        Packet DrainPacket(std::uint64_t nowMs) const noexcept
        {
            Packet p{}; p.kind = CommandKind::Drain; p.scope = s_.scope; p.sourceIdentity = s_.sourceIdentity;
            p.commandSequence = commandFloor_ == Maximum() ? 0U : commandFloor_ + 1U;
            p.intentSequence = intentFloor_; p.sourceSequence = sampleFloor_; p.sourceTimeMs = sampleTimeFloor_;
            p.observedAtMs = observedFloor_; p.issuedAtMs = nowMs; return p;
        }
    private:
        EDM46::Config config_{};
        ExecutionSnapshot s_{};
        std::uint64_t retiredSession_ = 0U, commandFloor_ = 0U, publicationFloor_ = 0U, lastNowMs_ = 0U;
        std::uint64_t intentFloor_ = 0U, sampleFloor_ = 0U, sampleTimeFloor_ = 0U, observedFloor_ = 0U;
        static constexpr std::uint64_t Maximum() noexcept { return (std::numeric_limits<std::uint64_t>::max)(); }
        bool Fail(Reason reason) noexcept { Abort(reason); return false; }
    };
    struct ConsumerSnapshot
    {
        ExecutionState state = ExecutionState::Idle;
        Reason reason = Reason::None;
        EDM46::Scope scope{};
        EDM26::LiveSourceIdentity sourceIdentity{};
        std::array<double, EDM46::AxisSlots> axisSpeedMmMin{};
        Receipt drainApplied{};
        std::uint64_t publication = 0U;
        bool pendingDrain = false, cancelled = false;
    };
    class ShadowConsumer
    {
    public:
        const ConsumerSnapshot& Snapshot() const noexcept { return s_; }
        bool Reset() noexcept
        {
            if (s_.state == ExecutionState::Running || s_.state == ExecutionState::Blocked || s_.pendingDrain) return false;
            const auto publication = s_.publication, retired = retiredSession_, command = commandFloor_;
            *this = ShadowConsumer{}; s_.publication = publication; retiredSession_ = retired; commandFloor_ = command; return true;
        }
        bool Start(const EDM46::Config& config, const EDM46::Scope& scope,
            const EDM46::IntentSnapshot& initial, std::uint64_t nowMs) noexcept
        {
            if (s_.state != ExecutionState::Idle) return Fail(Reason::InvalidLifecycle);
            if (scope.session <= retiredSession_) return Fail(Reason::RetiredSession);
            if (!ValidInitial(config, scope, initial, nowMs)) return Fail(Reason::InvalidConfig);
            config_ = config; s_.scope = scope; s_.sourceIdentity = initial.sourceIdentity;
            retiredSession_ = scope.session; lastNowMs_ = nowMs;
            intentFloor_ = initial.sequence; sampleFloor_ = initial.sourceSequence;
            sampleTimeFloor_ = initial.sourceTimeMs; observedFloor_ = initial.observedAtMs;
            s_.state = ExecutionState::Running; return true;
        }
        bool Apply(const Packet& packet, const Receipt& accepted, std::uint64_t nowMs, Receipt& output) noexcept
        {
            output = Receipt{};
            if (s_.state != ExecutionState::Running && s_.state != ExecutionState::Blocked) return Fail(Reason::InvalidLifecycle);
            if (nowMs < lastNowMs_ || packet.issuedAtMs < lastNowMs_ ||
                accepted.atMs > nowMs || accepted.atMs < packet.issuedAtMs) return Fail(Reason::Clock);
            if (accepted.stage != ReceiptStage::Accepted || accepted.publication != 0U ||
                !SamePacket(packet, accepted.packet)) return Fail(Reason::ReceiptMismatch);
            if (packet.commandSequence <= commandFloor_) return Fail(Reason::Sequence);
            if (!ValidPacket(packet, config_, s_.scope, s_.sourceIdentity, nowMs)) return Fail(Reason::InvalidPacket);
            if ((packet.kind == CommandKind::Velocity && (packet.intentSequence <= intentFloor_ ||
                packet.sourceSequence <= sampleFloor_ || packet.sourceTimeMs <= sampleTimeFloor_ ||
                packet.observedAtMs < observedFloor_)) ||
                (packet.kind == CommandKind::Drain && (packet.intentSequence < intentFloor_ ||
                 packet.sourceSequence < sampleFloor_ || packet.sourceTimeMs < sampleTimeFloor_ ||
                 packet.observedAtMs < observedFloor_ || (packet.sourceSequence == sampleFloor_ &&
                 packet.sourceTimeMs != sampleTimeFloor_)))) return Fail(Reason::Sequence);
            if (s_.publication == Maximum()) return Fail(Reason::CounterOverflow);
            commandFloor_ = packet.commandSequence; lastNowMs_ = nowMs;
            intentFloor_ = packet.intentSequence; sampleFloor_ = packet.sourceSequence;
            sampleTimeFloor_ = packet.sourceTimeMs; observedFloor_ = packet.observedAtMs;
            s_.axisSpeedMmMin = packet.axisSpeedMmMin;
            output = Receipt{packet, ReceiptStage::Applied, ++s_.publication, nowMs};
            s_.reason = Reason::None;
            if (packet.kind == CommandKind::Drain)
            { s_.pendingDrain = true; s_.drainApplied = output; s_.state = ExecutionState::Draining; }
            else s_.state = ExecutionState::Running;
            return true;
        }
        bool CompleteDrain(std::uint64_t nowMs, Receipt& output) noexcept
        {
            output = Receipt{};
            if (s_.state != ExecutionState::Draining || !s_.pendingDrain) return Fail(Reason::InvalidLifecycle);
            if (nowMs < lastNowMs_) return Fail(Reason::Clock);
            if (nowMs <= s_.drainApplied.atMs) { s_.reason = Reason::AwaitLaterClock; return false; }
            if (!AllSpeedsZero(s_)) return Fail(Reason::InvalidPacket);
            if (s_.publication == Maximum()) return Fail(Reason::CounterOverflow);
            output = Receipt{s_.drainApplied.packet, ReceiptStage::Completed, ++s_.publication, nowMs};
            s_.pendingDrain = false; s_.state = ExecutionState::Completed; s_.reason = Reason::None; lastNowMs_ = nowMs;
            return true;
        }
        // A staged caller must supply the producer's last accepted command
        // when clearing between Accept and Apply. This tombstones that exact
        // pending command too; the default clears only consumer-known work.
        void Neutralize(std::uint64_t cancelThroughCommand = 0U) noexcept
        {
            s_.axisSpeedMmMin.fill(0.0);
            if (cancelThroughCommand > commandFloor_) commandFloor_ = cancelThroughCommand;
            if (s_.state == ExecutionState::Running || s_.state == ExecutionState::Blocked)
            { s_.state = ExecutionState::Blocked; s_.reason = Reason::NonFresh; }
        }
        void Cancel() noexcept
        {
            s_.axisSpeedMmMin.fill(0.0); s_.pendingDrain = false;
            if (s_.state == ExecutionState::Idle || s_.state == ExecutionState::Cancelled) return;
            s_.cancelled = true; s_.state = ExecutionState::Cancelled; s_.reason = Reason::Cancelled;
        }
    private:
        EDM46::Config config_{};
        ConsumerSnapshot s_{};
        std::uint64_t retiredSession_ = 0U, commandFloor_ = 0U, lastNowMs_ = 0U;
        std::uint64_t intentFloor_ = 0U, sampleFloor_ = 0U, sampleTimeFloor_ = 0U, observedFloor_ = 0U;
        static constexpr std::uint64_t Maximum() noexcept { return (std::numeric_limits<std::uint64_t>::max)(); }
        bool Fail(Reason reason) noexcept { Cancel(); s_.state = ExecutionState::Fault; s_.reason = reason; return false; }
    };
    class ShadowExecution
    {
    public:
        const ExecutionSnapshot& Snapshot() const noexcept { return s_; }
        bool Reset() noexcept
        {
            if (s_.state == ExecutionState::Running || s_.state == ExecutionState::Blocked ||
                s_.state == ExecutionState::Draining || s_.pending) return false;
            if (!ledger_.Reset() || !consumer_.Reset()) return false;
            lastNowMs_ = lastIntentSequence_ = lastSourceSequence_ = lastSourceTimeMs_ = lastObservedMs_ = 0U;
            Sync(); return true;
        }
        bool Start(const EDM46::Config& config, const EDM46::Scope& scope,
            const EDM46::IntentSnapshot& initial, std::uint64_t nowMs) noexcept
        {
            if (s_.state != ExecutionState::Idle) return Fail(Reason::InvalidLifecycle);
            if (!ledger_.Start(config, scope, initial, nowMs)) return Fail(ledger_.Snapshot().reason);
            if (!consumer_.Start(config, scope, initial, nowMs)) return Fail(consumer_.Snapshot().reason);
            lastNowMs_ = nowMs; lastIntentSequence_ = initial.sequence;
            lastSourceSequence_ = initial.sourceSequence; lastSourceTimeMs_ = initial.sourceTimeMs;
            lastObservedMs_ = initial.observedAtMs; Sync(); return true;
        }
        const ExecutionSnapshot& Observe(const EDM46::IntentSnapshot& intent, bool authorityCurrent,
            std::uint64_t nowMs) noexcept
        {
            if (s_.state == ExecutionState::Cancelled || s_.state == ExecutionState::Fault) return s_;
            if (s_.state != ExecutionState::Running && s_.state != ExecutionState::Blocked)
            { Fail(Reason::InvalidLifecycle); return s_; }
            if (!authorityCurrent) { Fail(Reason::AuthorityLost); return s_; }
            if (!EDM46::SameScope(intent.scope, s_.scope)) { Fail(Reason::ScopeMismatch); return s_; }
            if (!EDM46::SameSource(intent.sourceIdentity, s_.sourceIdentity)) { Fail(Reason::SourceMismatch); return s_; }
            if (nowMs < lastNowMs_ || intent.observedAtMs < lastObservedMs_ || intent.observedAtMs > nowMs ||
                intent.sourceTimeMs > intent.observedAtMs || intent.sourceTimeMs < lastSourceTimeMs_)
            { Fail(Reason::Clock); return s_; }
            if (intent.sequence < lastIntentSequence_ || intent.sourceSequence < lastSourceSequence_ ||
                (intent.sourceSequence == lastSourceSequence_ && intent.sourceTimeMs != lastSourceTimeMs_))
            { Fail(Reason::Sequence); return s_; }
            lastNowMs_ = nowMs;
            if (intent.state == EDM46::IntentState::Revoked) { Cancel(); return s_; }
            if (intent.state == EDM46::IntentState::Blocked || intent.state == EDM46::IntentState::AwaitingFresh)
            {
                if (intent.ready || intent.acceptedFreshSample || !EDM46::AllSpeedsZero(intent) ||
                    intent.sequence != lastIntentSequence_ || intent.frame != EDM46::IntentFrame::None ||
                    intent.action != EDM25::ProcessAction::Wait)
                { Fail(Reason::InvalidIntent); return s_; }
                consumer_.Neutralize(ledger_.CommandFloor());
                if (!ledger_.Neutralize()) { Fail(ledger_.Snapshot().reason); return s_; }
                // A blocked sample advances the anti-replay observation floor
                // without inventing an accepted command or terminal receipt.
                lastIntentSequence_ = intent.sequence; lastSourceSequence_ = intent.sourceSequence;
                lastSourceTimeMs_ = intent.sourceTimeMs; lastObservedMs_ = intent.observedAtMs; Sync(); return s_;
            }
            if (intent.state != EDM46::IntentState::Ready || !intent.ready || !intent.acceptedFreshSample ||
                intent.sequence <= lastIntentSequence_ || intent.sourceSequence <= lastSourceSequence_ ||
                intent.sourceTimeMs <= lastSourceTimeMs_)
            { Fail(Reason::InvalidIntent); return s_; }
            if (ledger_.CommandFloor() == Maximum()) { Fail(Reason::CounterOverflow); return s_; }
            Packet packet{}; packet.scope = intent.scope; packet.sourceIdentity = intent.sourceIdentity;
            packet.commandSequence = ledger_.CommandFloor() + 1U; packet.intentSequence = intent.sequence;
            packet.sourceSequence = intent.sourceSequence; packet.sourceTimeMs = intent.sourceTimeMs;
            packet.observedAtMs = intent.observedAtMs; packet.issuedAtMs = nowMs;
            packet.frame = intent.frame; packet.action = intent.action; packet.signedSpeedMmMin = intent.signedSpeedMmMin;
            packet.axisSpeedMmMin = intent.axisSpeedMmMin;
            if (!Transact(packet, nowMs)) return s_;
            lastIntentSequence_ = intent.sequence; lastSourceSequence_ = intent.sourceSequence;
            lastSourceTimeMs_ = intent.sourceTimeMs; lastObservedMs_ = intent.observedAtMs; Sync(); return s_;
        }
        bool BeginDrain(std::uint64_t nowMs) noexcept
        {
            if (s_.state != ExecutionState::Running && s_.state != ExecutionState::Blocked) return Fail(Reason::InvalidLifecycle);
            // Clear first, even if validation or the logical clock fails.
            consumer_.Neutralize(ledger_.CommandFloor());
            if (nowMs < lastNowMs_) return Fail(Reason::Clock);
            if (ledger_.CommandFloor() == Maximum()) return Fail(Reason::CounterOverflow);
            if (!Transact(ledger_.DrainPacket(nowMs), nowMs)) return false;
            lastNowMs_ = nowMs; Sync(); return true;
        }
        DrainStatus PollDrain(const EDM46::Scope& scope, std::uint64_t nowMs) noexcept
        {
            if (!EDM46::SameScope(scope, s_.scope)) { Fail(Reason::ScopeMismatch); return DrainStatus::Invalid; }
            if (s_.state != ExecutionState::Draining && s_.state != ExecutionState::Completed) return DrainStatus::Invalid;
            if (nowMs < lastNowMs_) { Fail(Reason::Clock); return DrainStatus::Invalid; }
            if (s_.state == ExecutionState::Completed) { lastNowMs_ = nowMs; return DrainStatus::Ready; }
            Receipt receipt{};
            if (!consumer_.CompleteDrain(nowMs, receipt))
            {
                if (consumer_.Snapshot().reason == Reason::AwaitLaterClock) return DrainStatus::Wait;
                Fail(consumer_.Snapshot().reason); return DrainStatus::Invalid;
            }
            if (!ledger_.Complete(receipt, nowMs)) { Fail(ledger_.Snapshot().reason); return DrainStatus::Invalid; }
            lastNowMs_ = nowMs; Sync(); return DrainStatus::Ready;
        }
        void Cancel() noexcept { consumer_.Cancel(); ledger_.Cancel(); Sync(); }
    private:
        ExecutionLedger ledger_{};
        ShadowConsumer consumer_{};
        ExecutionSnapshot s_{};
        std::uint64_t lastNowMs_ = 0U, lastIntentSequence_ = 0U, lastSourceSequence_ = 0U;
        std::uint64_t lastSourceTimeMs_ = 0U, lastObservedMs_ = 0U;
        static constexpr std::uint64_t Maximum() noexcept { return (std::numeric_limits<std::uint64_t>::max)(); }
        void Sync() noexcept { s_ = ledger_.Snapshot(); s_.axisSpeedMmMin = consumer_.Snapshot().axisSpeedMmMin; }
        bool Fail(Reason reason) noexcept { consumer_.Cancel(); ledger_.Abort(reason); Sync(); return false; }
        bool Transact(const Packet& packet, std::uint64_t nowMs) noexcept
        {
            if (!ledger_.Accept(packet, nowMs)) return Fail(ledger_.Snapshot().reason);
            Receipt receipt{};
            if (!consumer_.Apply(packet, ledger_.Snapshot().lastAccepted, nowMs, receipt)) return Fail(consumer_.Snapshot().reason);
            if (!ledger_.Apply(receipt, nowMs)) return Fail(ledger_.Snapshot().reason);
            Sync(); return true;
        }
    };
    static_assert(std::is_trivially_copyable<Packet>::value, "EDM47 packets remain bounded value storage.");
    static_assert(sizeof(ShadowExecution) <= 8192U, "EDM47 shadow handoff storage is bounded.");
    inline const char* StateName(ExecutionState state) noexcept
    {
        switch (state)
        {
        case ExecutionState::Idle: return "IDLE"; case ExecutionState::Running: return "RUNNING";
        case ExecutionState::Blocked: return "BLOCKED"; case ExecutionState::Draining: return "DRAINING";
        case ExecutionState::Completed: return "COMPLETED"; case ExecutionState::Cancelled: return "CANCELLED";
        case ExecutionState::Fault: return "FAULT";
        } return "UNKNOWN";
    }
    inline const char* KindName(CommandKind kind) noexcept
    { return kind == CommandKind::Velocity ? "VELOCITY" : kind == CommandKind::Drain ? "DRAIN" : "UNKNOWN"; }
    inline const char* StageName(ReceiptStage stage) noexcept
    {
        switch (stage) { case ReceiptStage::None: return "NONE"; case ReceiptStage::Accepted: return "ACCEPTED";
        case ReceiptStage::Applied: return "APPLIED"; case ReceiptStage::Completed: return "COMPLETED"; } return "UNKNOWN";
    }
    inline const char* ReasonName(Reason reason) noexcept
    {
        switch (reason)
        {
#define EDM47_REASON(name, label) case Reason::name: return label
        EDM47_REASON(None, "NONE"); EDM47_REASON(InvalidLifecycle, "INVALID_LIFECYCLE");
        EDM47_REASON(InvalidConfig, "INVALID_CONFIG"); EDM47_REASON(ScopeMismatch, "SCOPE_MISMATCH");
        EDM47_REASON(SourceMismatch, "SOURCE_MISMATCH"); EDM47_REASON(InvalidIntent, "INVALID_INTENT");
        EDM47_REASON(InvalidPacket, "INVALID_PACKET"); EDM47_REASON(Clock, "CLOCK"); EDM47_REASON(Stale, "STALE");
        EDM47_REASON(Sequence, "SEQUENCE"); EDM47_REASON(Busy, "BUSY"); EDM47_REASON(ReceiptMismatch, "RECEIPT_MISMATCH");
        EDM47_REASON(AuthorityLost, "AUTHORITY_LOST"); EDM47_REASON(CounterOverflow, "COUNTER_OVERFLOW");
        EDM47_REASON(AwaitLaterClock, "AWAIT_LATER_CLOCK"); EDM47_REASON(NonFresh, "NON_FRESH");
        EDM47_REASON(Cancelled, "CANCELLED"); EDM47_REASON(RetiredSession, "RETIRED_SESSION");
#undef EDM47_REASON
        } return "UNKNOWN";
    }
    inline const char* ExecutionStateName(ExecutionState state) noexcept { return StateName(state); }
    inline const char* ExecutionReasonName(ExecutionReason reason) noexcept { return ReasonName(reason); }
}
